// Tiny base64 PNG placeholders for internal icons. Replace with richer art as needed.
export const Icons = {
  slot: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAIUlEQVQoU2NkYGD4z0AEMMDEgDgQYFQAI2QwQhGQYQAA0H0J1zN2i6UAAAAASUVORK5CYII=',
  chip: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAKUlEQVQoU2NkYGBg+M8ABYwMjAwMDIwM/8fQbAgGJgRjA4jGQIAj0gD6s0cQrgAAAABJRU5ErkJggg==',
  wheel: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAIElEQVQoU2NkYGD4z0ABYGBgYGBQJgYGBkYAGc0A8KZb3S8AAAAASUVORK5CYII=',
  wallet: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAJElEQVQoU2NkYGBg+M8ABYyMDIYgGJgRjA4jGYgYgQGAAk8ABQ0BcbFHq77AAAAAElFTkSuQmCC',
  crown: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAJ0lEQVQoU2NkYGBg+M8ABYxgYGBQJgYGBsZgGAQjGQYgAAcHAAH+gD2f0Z9HAAAAAElFTkSuQmCC',
  warning: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAIklEQVQoU2NkYGD4z0AEMDAwMDAgGJgRjIYBBgAA6SwA4h8o/vcAAAAASUVORK5CYII=',
  hearts: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAJElEQVQoU2NkYGBg+M8ABYyMDKBQYGBgMDgQYgQGAAk8ABF1AcdwQv7rAAAAAElFTkSuQmCC',
};

export type IconName = keyof typeof Icons;

export function iconBuffer(name: IconName): Buffer {
  return Buffer.from(Icons[name], 'base64');
}
